sudo: required
services:
    - docker 

before_install:
    - docker build -t daciandiaconeasa/docker-react -f Dockerfile.dev .

script:
    - docker run daciandiaconeasa/docker-react npm run test -- --coverage